[package]
name = "branch-diff"
version = "0.1.0"
edition = "2024"
authors = ["Hadrian Hughes <hadrianhughes@gmail.com>"]
license = "GPL-3.0-or-later"

[dependencies]
ratatui = "0.29.0"
crossterm = "0.28.1"
git2 = "0.20.2"
clap = { version = "4.5.53", features = ["derive"] }
textwrap = "0.16.2"
